apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: agent
    app.kubernetes.io/managed-by: sbd-operator
    app.kubernetes.io/name: sbd-agent
    app.kubernetes.io/part-of: sbd-operator
  name: sbd-operator-sbd-agent
