apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: sbd-operator-metrics-auth-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sbd-operator-metrics-auth-role
subjects:
- kind: ServiceAccount
  name: sbd-operator-sbd-operator-controller-manager
  namespace: sbd-operator-system
