apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    rbac.ext-remediation/aggregate-to-ext-remediation: "true"
  name: sbd-operator-ext-remediation
rules:
- apiGroups:
  - medik8s.medik8s.io
  resources:
  - storagebasedremediationtemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - medik8s.medik8s.io
  resources:
  - storagebasedremediations
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
