apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sbd-operator
  name: sbd-operator-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sbd-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: sbd-operator-sbd-operator-controller-manager
  namespace: sbd-operator-system
