apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: agent
    app.kubernetes.io/managed-by: sbd-operator
    app.kubernetes.io/name: sbd-agent
    app.kubernetes.io/part-of: sbd-operator
  name: sbd-operator-sbd-agent-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sbd-operator-sbd-agent-role
subjects:
- kind: ServiceAccount
  name: sbd-operator-sbd-agent
  namespace: sbd-operator-system
