apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sbd-operator
    app.kubernetes.io/part-of: sbd-operator
  name: sbd-operator-sbd-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sbd-operator-manager-role
subjects:
- kind: ServiceAccount
  name: sbd-operator-sbd-operator-controller-manager
  namespace: sbd-operator-system
