nameReference:
- kind: Service
  version: v1
  fieldSpecs:
  - path: webhooks/clientConfig/service/name
    kind: ValidatingAdmissionWebhook

namespace:
- kind: ValidatingAdmissionWebhook
  group: admissionregistration.k8s.io
  path: webhooks/clientConfig/service/namespace
  create: false

- kind: Service
  version: v1
  path: metadata/namespace
  create: true 