## Append samples of your project ##
resources:
- medik8s_v1alpha1_storagebasedremediation.yaml
- medik8s_v1alpha1_storagebasedremediationtemplate.yaml
- medik8s_v1alpha1_sbdconfig.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
