apiVersion: medik8s.medik8s.io/v1alpha1
kind: SBDRemediationTemplate
metadata:
  labels:
    app.kubernetes.io/name: sbd-operator
    app.kubernetes.io/managed-by: kustomize
  name: sbdremediationtemplate-sample
spec:
  # TODO(user): Add fields here
