apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- sbd-agent-scc.yaml

# Labels to add to all resources
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: openshift-resources
    app.kubernetes.io/name: sbd-operator
