apiVersion: medik8s.medik8s.io/v1alpha1
kind: SBDConfig
metadata:
  name: test-sbdconfig
spec:
  imagePullPolicy: Always 
  namespace: sbd-system
  petIntervalMultiple: 4
  sbdWatchdogPath: /dev/watchdog
  staleNodeTimeout: 1h
  watchdogTimeout: 60s

